### PR TITLE
add support for tag-list on register

### PR DESCRIPTION
**Pull request by takumakanari**
this p-r makes it possible to set also `tag-list` to runner by specifying  `RUNNER_TAG_LIST` to Docker env.

### CODE REVIEW

**Comment by karcaw** [comment]
Please add this!

**Comment by oomathias** [comment]
Adding `RUNNER_TAG_LIST` should work by default, since `gitlab-ci-multi-runner` watch `RUNNER_TAG_LIST`.

**Comment by djskinner-sky** [comment]
Yeah I just found out you can simply set environment variables to configure on register. For example I added $DOCKER_DISABLE_CACHE=true` for my requirements. Run `gitlab-ci-multi-runner register
--help` in the container for all the options are corresponding environment variable names.

**Comment by takumakanari** [comment]
oh I see, if so I'll close this p-r.

**Pull request closed without merging**
